import { useEffect, useRef, useState } from 'react';
import { createSpeechRecognition, speak, infer, createBrowserCall } from './lib/voice';
import { loadLeafRecords, saveLeafRecord } from './lib/supabase';
import './style.css';

type Tab = 'Chat' | 'Calls' | 'Contacts' | 'Memory' | 'Automations' | 'Settings';
type Contact = { id: string | number; name: string; phone: string; email?: string; note?: string };

function formatPhone(value: string) {
  const raw = value.trim();
  const hasPlus = raw.startsWith('+');
  const digits = raw.replace(/\D/g, '');
  if (!digits) return hasPlus ? '+' : '';
  const normalized = !hasPlus && digits.length <= 10 ? `1${digits}` : digits;
  const country = normalized.startsWith('1') ? '+1' : (hasPlus ? '+' : '+');
  const local = normalized.startsWith('1') ? normalized.slice(1, 11) : normalized.slice(country === '+' && hasPlus ? 1 : 0, 15);
  if (country === '+1') {
    const area = local.slice(0, 3), prefix = local.slice(3, 6), line = local.slice(6, 10);
    return `${country} ${area}${local.length > 3 ? `-${prefix}` : ''}${local.length > 6 ? `-${line}` : ''}`;
  }
  return `${country}${local}`;
}

function Calls() { const [active,setActive]=useState(false),[elapsed,setElapsed]=useState(0),[level,setLevel]=useState(0),[status,setStatus]=useState('Ready to call'); const call=useRef<{stop:()=>void}|null>(null),timer=useRef<number>(); const end=()=>{call.current?.stop();call.current=null;if(timer.current)window.clearInterval(timer.current);setActive(false);setStatus('Call ended');setElapsed(0);setLevel(0)}; const start=async()=>{try{window.speechSynthesis.cancel();setStatus('Requesting microphone…');call.current=await createBrowserCall(setLevel);setActive(true);setStatus('Live · listening');timer.current=window.setInterval(()=>setElapsed(x=>{if(x>=179){end();return 180}return x+1}),1000)}catch{setStatus('Microphone permission is required')}}; useEffect(()=>()=>end(),[]); return <section className="panel call-panel"><h2>Calls</h2><div className={active?'call-state live':'call-state'}><div className="orb">●</div><h3>{active?'Leaf is listening':'Browser voice call'}</h3><p>{status}</p>{active&&<><strong>{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')} / 3:00</strong><button className="danger" onClick={end}>End call</button></>}{!active&&<button onClick={start}>Start browser call</button>}</div></section> }

function Contacts(){ const [contacts,setContacts]=useState<Contact[]>([]),[loading,setLoading]=useState(true),[phone,setPhone]=useState(''); useEffect(()=>{loadLeafRecords('contacts').then(rows=>setContacts(rows.map((r:any)=>({id:r.id??r.name,name:r.name??'',phone:formatPhone(r.phone??r.phone_number??''),email:r.email,note:r.note})))).catch(()=>setContacts([])).finally(()=>setLoading(false))},[]); const add=async()=>{if(!phone.trim())return;const record=await saveLeafRecord('contacts',{phone:formatPhone(phone)});setContacts(c=>[{id:(record as any).id??Date.now(),name:(record as any).name??'New contact',phone:formatPhone((record as any).phone??phone)},...c]);setPhone('')}; return <section className="panel"><h2>Contacts</h2><p className="muted">Contacts are loaded from Supabase. No starter contacts are shown.</p><div className="composer"><input value={phone} onChange={e=>setPhone(formatPhone(e.target.value))} placeholder="Phone number (+1 by default)" inputMode="tel"/><button onClick={add}>Add</button></div>{loading?<p>Loading…</p>:contacts.length===0?<p className="muted">No contacts yet.</p>:contacts.map(c=><div className="row" key={c.id}><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><div className="grow"><strong>{c.name}</strong><small>{formatPhone(c.phone)}</small></div></div>)}</section> }

export default function App(){const [tab,setTab]=useState<Tab>('Chat'),[text,setText]=useState(''),[messages,setMessages]=useState<string[]>(['Hey Tanner. I’m ready when you are.']),[listening,setListening]=useState(false);const recognition=useRef<any>(null);const toggle=()=>{if(listening){recognition.current?.stop();setListening(false);return}window.speechSynthesis.cancel();recognition.current=createSpeechRecognition(r=>setText(r.text),e=>setText(`Speech error: ${e}`));if(!recognition.current){setText('Speech recognition is unavailable. Try Chrome or Edge.');return}recognition.current.start();setListening(true)};const send=async()=>{if(!text.trim())return;const prompt=text.trim();setMessages(m=>[...m,prompt]);setText('');try{const answer=await infer(prompt);setMessages(m=>[...m,answer]);speak(answer);await saveLeafRecord('chat',{role:'user',content:prompt})}catch{setMessages(m=>[...m,'I couldn’t reach the free inference provider right now.'])}};useEffect(()=>()=>recognition.current?.stop(),[]);return <div className="app"><aside><h1>✦ Leaf</h1><p className="muted">Tanner’s personal workspace</p>{(['Chat','Calls','Contacts','Memory','Automations','Settings'] as Tab[]).map(x=><button className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside><main><header><span>{tab.toUpperCase()}</span><b className="status">● All systems operational</b></header>{tab==='Chat'?<section className="chat"><div className="messages">{messages.map((m,i)=><div className={i%2?'bubble user':'bubble'} key={i}><small>{i%2?'You':'Leaf'}</small><div>{m}</div></div>)}</div><div className="composer"><button onClick={toggle}>{listening?'◼':'🎙'}</button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={listening?'Listening…':'Message Leaf…'}/><button onClick={send}>Send</button></div></section>:tab==='Calls'?<Calls/>:tab==='Contacts'?<Contacts/>:<section className="panel"><h2>{tab}</h2><p>Connected to Supabase for Leaf data and settings.</p></section>}</main></div>}
