import { useEffect, useRef, useState } from 'react';
import { createSpeechRecognition, speak, infer } from './lib/voice';
import { saveLeafRecord } from './lib/supabase';
import './style.css';

type Tab = 'Chat' | 'Calls' | 'Contacts' | 'Memory' | 'Automations' | 'Settings';
export default function App() {
 const [tab,setTab]=useState<Tab>('Chat'); const [text,setText]=useState(''); const [messages,setMessages]=useState<string[]>(['Hey Tanner. I’m ready when you are.']); const [listening,setListening]=useState(false); const recognition=useRef<any>(null);
 const toggleSTT=()=>{ if(listening){recognition.current?.stop();setListening(false);return;} recognition.current=createSpeechRecognition(r=>setText(r.text),e=>setText(`Speech error: ${e}`)); if(!recognition.current){setText('Speech recognition is unavailable in this browser. Try Chrome or Edge.');return;} recognition.current.start();setListening(true); };
 const send=async()=>{if(!text.trim())return;const prompt=text.trim();setMessages(m=>[...m,prompt]);setText('');try{const answer=await infer(prompt);setMessages(m=>[...m,answer]);speak(answer);await saveLeafRecord('chat',{role:'user',content:prompt});}catch(e){setMessages(m=>[...m,'I couldn’t reach the free inference provider right now.']);}};
 useEffect(()=>()=>recognition.current?.stop(),[]);
 return <div className="app"><aside><h1>✦ Leaf</h1><p className="muted">Tanner’s personal workspace</p>{(['Chat','Calls','Contacts','Memory','Automations','Settings'] as Tab[]).map(x=><button className={tab===x?'nav active':'nav'} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside><main><header><span>{tab.toUpperCase()}</span><b className="status">● All systems operational</b></header>{tab==='Chat'?<section className="chat"><div className="messages">{messages.map((m,i)=><div className={i%2?'bubble user':'bubble'} key={i}><small>{i%2?'You':'Leaf'}</small><div>{m}</div></div>)}</div><div className="composer"><button onClick={toggleSTT} title="Speech to text">{listening?'◼':'🎙'}</button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={listening?'Listening…':'Message Leaf…'}/><button onClick={send}>Send</button></div><p className="hint">Free stack: Web Speech API · native browser voice · Pollinations inference</p></section>:<section className="panel"><h2>{tab}</h2><p>This workspace is connected to Supabase for contacts, calls, chat, memory, automations, and settings.</p>{tab==='Calls'&&<p>Browser WebRTC/microphone calling is available from the free voice module, with audio-level visualization hooks and a three-minute cutoff for the call UI.</p>}{tab==='Settings'&&<p>Provider: Pollinations (free fallback) · TTS: native speechSynthesis · STT: SpeechRecognition</p>}</section>}</main></div>;
}